//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
#include "main.hpp"
#include "catch.hpp"

TEST_CASE("Test for division 1", "Sample 1")
{
    REQUIRE(calc(3, '/', -36) == Approx(-0.0833333333));
}

TEST_CASE("Test for division 2", "Sample 2")
{
    REQUIRE(calc(3.9, '/', -5) == Approx(-0.78));
}

TEST_CASE("Test for division 3", "Sample 3")
{
    REQUIRE(calc(3.9, '/', 16.89) == Approx(0.2309058615));
}

TEST_CASE("Test for division 4", "Sample 4")
{
    REQUIRE(calc(3, '/', -45.2) == Approx(-0.06637168142));
}

TEST_CASE("Test for division 5", "Sample 5")
{
    REQUIRE(std::isinf(calc(15.69, '/', 0.0)));
}

TEST_CASE("Test for division 6", "Sample 6")
{
    REQUIRE(std::isnan(calc(0.0, '/', 0.0)));
}
