//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
#include "main.hpp"
#include "catch.hpp"

TEST_CASE("Test for modulus 1", "Sample 1")
{
    REQUIRE(calc(36, '%', 3) == 0);
}

TEST_CASE("Test for modulus 2", "Sample 2")
{
    REQUIRE(calc(262.75, '%', 14.2) == 11);
}

TEST_CASE("Test for modulus 3", "Sample 3")
{
    REQUIRE(calc(16.89, '%', -3.89) == 1);
}

TEST_CASE("Test for modulus 4", "Sample 4")
{
    REQUIRE(calc(-32.8, '%', 6) == -3);
}

TEST_CASE("Test for modulus 5", "Sample 5")
{
    REQUIRE(calc(16, '%', 3) == 1);
}

TEST_CASE("Test for modulus 6", "Sample 6")
{
    REQUIRE(calc(29.0, '%', 7.2) == 1);
}