//NRMN: DO NOT EDIT THIS FILE. NOT YOUR CONCERN.
#include "main.hpp"
#include "catch.hpp"

TEST_CASE("Test for multiplication 1", "Sample 1")
{
    REQUIRE(calc(3, '*', -36) == -108);
}

TEST_CASE("Test for multiplication 2", "Sample 2")
{
    REQUIRE(calc(3.9, '*', -5) == Approx(-19.5));
}

TEST_CASE("Test for multiplication 3", "Sample 3")
{
    REQUIRE(calc(3.9, '*', 16.89) == Approx(65.871));
}

TEST_CASE("Test for multiplication 4", "Sample 4")
{
    REQUIRE(calc(3, '*', -45.2) == Approx(-135.6));
}

TEST_CASE("Test for multiplication 5", "Sample 5")
{
     REQUIRE(calc(0, '*', 15.69) == 0);
}

TEST_CASE("Test for multiplication 6", "Sample 6")
{
    REQUIRE(calc(112.369, '*', 96.333) == Approx(10824.84288));
}
